lang: en
title: commandini's tech blog
author: Fakih Karademir
social:
  github: commandini
description: "{mathematics, algorithms and programming puzzles}"
google_analytics: G-5LLEJSRR1Y
theme: jekyll-theme-cayman
timezone: Europe/Amsterdam
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
